// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATH1Vg4zZ1AWqP-o53mXioQDo_qzLNSTs',
    appId: '1:548026878700:web:fe5a67a14d72171d27f3c9',
    messagingSenderId: '548026878700',
    projectId: 'digital-cardapio',
    authDomain: 'digital-cardapio.firebaseapp.com',
    storageBucket: 'digital-cardapio.appspot.com',
    measurementId: 'G-S2PJ6V2113',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPdNEFLNt4Y5tngYiGrij80irZKqSVgOo',
    appId: '1:548026878700:android:139bbae8e500939527f3c9',
    messagingSenderId: '548026878700',
    projectId: 'digital-cardapio',
    storageBucket: 'digital-cardapio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGRgKRxT4YOMKXSWqMgSlNe7KhNiCBs2g',
    appId: '1:548026878700:ios:1751b1776e15145927f3c9',
    messagingSenderId: '548026878700',
    projectId: 'digital-cardapio',
    storageBucket: 'digital-cardapio.appspot.com',
    iosClientId: '548026878700-s5cimv2e267ldgibe3ss56fdnf83q0a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.forFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGRgKRxT4YOMKXSWqMgSlNe7KhNiCBs2g',
    appId: '1:548026878700:ios:1751b1776e15145927f3c9',
    messagingSenderId: '548026878700',
    projectId: 'digital-cardapio',
    storageBucket: 'digital-cardapio.appspot.com',
    iosClientId: '548026878700-s5cimv2e267ldgibe3ss56fdnf83q0a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.forFood',
  );
}
